### ISSUE TITLE
TypeError: type object got multiple values for keyword argument 'log'

### ISSUE THREAD

**Issue by Ethnical** [geohot/qira#192]
Hi everyone, 
When i use Qira ./bin/ls i got this error 

Ubunutu x64 bits on /bin/ls : 

`Traceback (most recent call last):
  File "/home/reverse/qira-1.2/middleware/qira.py", line 104, in <module>
    qira_webserver.run_server(args, program)
  File "/home/reverse/qira-1.2/middleware/qira_webserver.py", line 437, in run_server
    socketio.run(app, host=qira_config.HOST, port=qira_config.WEB_PORT, log=open("/dev/null", "w"))
  File "/home/reverse/qira-1.2/venv/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 529, in run
    log=log, **kwargs)
TypeError: type object got multiple values for keyword argument 'log'`

![image](https://user-images.githubusercontent.com/23560242/29003206-afbf2ba4-7ab2-11e7-991e-3c7daa405fd1.png)

Thanks if somebody can help me ^^

**Comment by Antoxyde** [comment]
Same here, ubuntu 17.04 x86-64, one week after installation, everything up to date.
The installation of qira ended without any errors.
![screenshot from 2017-08-06 14-10-57](https://user-images.githubusercontent.com/17276416/29003230-18d08fde-7ab3-11e7-8054-ce85df425de5.png)

**Comment by mpex** [comment]
Flask-SocketIO got an update (to 2.9.2) which obviously broke qira. You can simply downgrade this module.
Here is how I did it:

`source <qira-dir>/venv/bin/activate`
`pip uninstall Flask-SocketIO`
`pip install Flask-SocketIO==2.9.1`
`deactivate`

After that qira starts properly

**Comment by rlyshw** [comment]
Seems like requirements.txt should be updated to specify
flask-socketio==2.9.1
