### ISSUE TITLE
Can't install qira on fedora 30 : memfd_create error

### ISSUE THREAD

**Issue by hetjagani** [geohot/qira#236]
I have fetched and installed all the dependencies that are required because I thought that might be the problem. But then too the following error is coming in the install process. Please improve the install process to completely support fedora. Below is the error :
```
util/memfd.c:43:12: error: static declaration of ‘memfd_create’ follows non-static declaration
   43 | static int memfd_create(const char *name, unsigned int flags)
      |            ^~~~~~~~~~~~
In file included from /usr/include/bits/mman-linux.h:111,
                 from /usr/include/bits/mman.h:34,
                 from /usr/include/sys/mman.h:41,
                 from /home/het/qira-1.3/tracers/qemu/qemu-latest/include/qemu/osdep.h:142,
                 from util/memfd.c:28:
/usr/include/bits/mman-shared.h:50:5: note: previous declaration of ‘memfd_create’ was here
   50 | int memfd_create (const char *__name, unsigned int __flags) __THROW;
      |     ^~~~~~~~~~~~
make: *** [/home/het/qira-1.3/tracers/qemu/qemu-latest/rules.mak:57: util/memfd.o] Error 1
make: *** Waiting for unfinished jobs....

```

**Comment by meowmeowxw** [comment]
Same error on arch linux

**Comment by lumoe** [comment]
@hetjagani Were you able to resolve this issue?

**Comment by hetjagani** [comment]
Try removing static from util/memfd.c:43:12

**Comment by c10udlnk** [comment]
I used `apt install qemu` to install QEMU separately and commented out the statement for installing QEMU in `./install.sh`.  Then the error did not recur. (WSL too)
(but unluckily another error happened in the following process. X_X
